### ISSUE TITLE
Custom FEDC

### ISSUE THREAD

**Issue by Doomsdayrs** [flathub/org.freedesktop.Sdk.Extension.texlive#140]
I noticed a lot of PRs are FEDC targeting 21.08, perhaps a custom FEDC only targeting supported branches?

An alternate solution is to change the main branch to 23.08

**Comment by jakobjakobson13** [comment]
> An alternate solution is to change the main branch to 23.08

I think that's the way to go. Unfortunately, i don't gave the proper permissions.

**Comment by hfiguiere** [comment]
file an issue https://github.com/flathub/flathub/issues/new

**Comment by jakobjakobson13** [comment]
Closed by https://github.com/flathub/flathub/issues/4606#event-10674684340
