### ISSUE TITLE
Possibility to point to files of a different flatpak package

### ISSUE THREAD

**Issue by jakobjakobson13** [flathub/org.freedesktop.Sdk.Extension.texlive#16]
@barthalion I guess this question goes to you (with the background of this comment https://github.com/flathub/de.wolfvollprecht.UberWriter/pull/9#issuecomment-549943180): Currently each flatpak package that uses the texlive extension copies the complete content of this extension into its own directories. So assuming more latex editors will come to flatpak and you install like 3 or 4 editors you end up with 3 or 4 exact copies of the same latex files.
So I wondered if you could just point to the texlive extension in a way that is agnostic regarding the system and therefore minimize the package size of the respective editors and minimize the redundancy of the files. Also programs like for example `lyx` heavily rely on other programs like  `inkscape` and putting all their optional requirements into one package would result in a really huge package.
So is this pointing to other packages/extensions possible with extensions or can it be only be done with runtimes?

Thanks in advance for your answer and the work you put into the maintaining of all the packages.

**Comment by TingPing** [comment]
Isn't this the same discussion as https://github.com/flatpak/flatpak/issues/3199

No `flatpak` is not designed like traditional package managers and you cannot package every dependency like so.

**Comment by jakobjakobson13** [comment]
> Isn't this the same discussion as [flatpak/flatpak#3199](https://github.com/flatpak/flatpak/issues/3199)

Yes, it's similar but not totally equal. But the difference is not that big.

> No `flatpak` is not designed like traditional package managers and you cannot package every dependency like so.

Okay. So I'll close this bug report.
