### ISSUE TITLE
Way to run binaries in terminal

### ISSUE THREAD

**Issue by machitgarha** [flathub/org.freedesktop.Sdk.Extension.texlive#172]
I want to run a binary from terminal, like `tlmgr` or `luatex`. Is this possible?

**Comment by jakobjakobson13** [comment]
Hi,

it is possible by running for example `$ flatpak run --command=bash org.gnome.Sdk `.

https://docs.flatpak.org/en/latest/flatpak-command-reference.html gives the following additional information:
> 
> --command=COMMAND
> 
>     The command to use. If this option is not specified, the first executable found in files/bin is used.
> 
>     Note that the command is used when the application is run via flatpak run, and does not affect what gets executed when the application is run in other ways, e.g. via the desktop file or D-Bus activation.

**Comment by machitgarha** [comment]
Right, I can run `lualatex` using:

```
flatpak run --command=/usr/lib/sdk/texlive/bin/x86_64-linux/lualatex org.freedesktop.Sdk//23.08
```

But is there a way to run `tlmgr` to update packages, or are the packages immutable? (Running `tlmgr` using the command above doesn't work)

**P.S.:** Actually, this was my main question. :)

**Comment by jakobjakobson13** [comment]
In principle you should be able to run `tlmgr` (But not with the `org.freedesktop.Sdk.Extension.texlive` package as the perl paths are not set. Use one of the LaTeX editors instead.) but you shouldn't be able to update the packages as they are immutable.

**Comment by machitgarha** [comment]
Alright, thanks.
