### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by hfiguiere** [flathub/org.freedesktop.Sdk.Extension.texlive#37]
Right now this SDK is not build for aarch64, which block every other pacakge relying on it.

#22 could be a solution for this.

**Comment by fedelibre** [comment]
Pull #34 should have closed this issue, right?

However, I still have a problem. When trying to build my app for aarch64, [one of its modules, lilypond,](https://flathub.org/builds/#/builders/54/builds/2902) fails because of missing packages (NOTE: the x86_64 doesn't fail):

```
ERROR: Please install required programs:  mf-nowin mf mfw mfont mpost kpsewhich metapost CTAN package (texlive-metapost)
```

**Comment by fedelibre** [comment]
Or maybe I should pass some configuration option? I'll check later...

**Comment by hfiguiere** [comment]
> Or maybe I should pass some configuration option? I'll check later...

That's because of the `PATH`:
I have the following patch here for lillypond:
```diff
     build-options:
-      env:
-        PATH: /usr/lib/sdk/texlive/bin/x86_64-linux:/usr/lib/sdk/texlive/bin:/usr/bin:/app/bin
+      arch:
+        aarch64:
+          prepend-path: /usr/lib/sdk/texlive/bin/aarch64-linux:/usr/lib/sdk/texlive/bin
+        x86_64:
+          prepend-path: /usr/lib/sdk/texlive/bin/x86_64-linux:/usr/lib/sdk/texlive/bin

   # OpenJPEG is needed to build Poppler
   - shared-modules/openjpeg/openjpeg.json
```

**Comment by hfiguiere** [comment]
BTW closing this issue since it is in.

**Comment by fedelibre** [comment]
Thanks! That line caught my attention but I didn't know prepend-path
