### ISSUE TITLE
$PATH not properly set in enable.sh for 20.08

### ISSUE THREAD

**Issue by duesenfranz** [flathub/org.freedesktop.Sdk.Extension.texlive#41]
`enable.sh` refers to the variable `${FLATPAK_ARCH}`, which is only available during build:
https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/blob/e70acb66e9c8c34e95b73065ecf73e5caabc19b1/org.freedesktop.Sdk.Extension.texlive.yml#L156 

This means that e.g. using this extension with the visual studio code and `FLATPAK_ENABLE_SDK_EXT=texlive` fails, as visual studio [will run `enable.sh`](https://github.com/flathub/com.visualstudio.code/blob/d15640b2d58417ef4061d5631fa999d061eb066e/code.sh#L54).

Inside the visual studio code flatpak,
`echo $PATH` now yields
`/usr/lib/sdk/texlive/bin/-linux:/usr/lib/sdk/texlive/bin:/app/bin:/usr/bin:/home/jona/.var/app/com.visualstudio.code/data/node_modules/bin`.

**Comment by jakobjakobson13** [comment]
Could you check if #42 solves the issue?

**Comment by duesenfranz** [comment]
@jakobjakobson13, thanks for the PR! Yes, I can confirm #42 fixes this problem. Using [jakobjakobson13:expand_variable](https://github.com/jakobjakobson13/org.freedesktop.Sdk.Extension.texlive/tree/expand_variable) makes vs code work with texlive flawlessly.

**Comment by jakobjakobson13** [comment]
Has been fixed in #42.

**Comment by duesenfranz** [comment]
Thanks! :)
