### ISSUE TITLE
TeX Live 2021 released

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub/org.freedesktop.Sdk.Extension.texlive#43]
TeX Live 2021 has been released: https://www.preining.info/blog/2021/04/tex-live-2021-released/

**Comment by hfiguiere** [comment]
The build failed.

**Comment by hfiguiere** [comment]
I have triggered a rebuild as it seems to be relate to the builder for aarch64 timing out.

**Comment by jakobjakobson13** [comment]
Well, it failed three times now as far as I can tell, but that happened also with earlier builds (see [https://github.com/flathub/flathub/issues/2077](https://github.com/flathub/flathub/issues/2077)). Perhaps we have to ask the flathub core maintainers for an increase of the timeout.

**Comment by msrn** [comment]
Any solution for this? Would be nice to have the newest TeXLive.

**Comment by jakobjakobson13** [comment]
bot, build org.freedesktop.Sdk.Extension.texlive

**Comment by hfiguiere** [comment]
bot doesn't follow issues...

**Comment by jakobjakobson13** [comment]
Was fixed in commit d2fc5c7ff8838c9ec2e211cbdcf1358d8ffb2e0f .

	TeX Live Sdk extension - LaTeX packages and tools

	     Kennung: org.freedesktop.Sdk.Extension.texlive
		 Ref: runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/21.08
	 Architektur: x86_64
	       Zweig: 21.08
	     Version: 2020.04.06
	    Ursprung: flathub
	    Sammlung: org.flathub.Stable
	Installation: user
	 Installiert: 7,5 GB

	      Commit: e60f2fc6050a325d6311275a1e9509d841d031ba1f33d6d3803e31e5e9508b17
	     Subject: Update SDK and runtime to 21.08 (d2fc5c7f)
		Date: 2021-10-21 08:55:18 +0000
