### ISSUE TITLE
biber is missing

### ISSUE THREAD

**Issue by cunidev** [flathub/org.freedesktop.Sdk.Extension.texlive#46]
I am using the Setzer LaTeX editor from Flathub, and on compilation I get an error that biber is missing.

In case this module is the cause, since biber is the de-facto backend for bibliography management, would it be possible to add this to the texlive extension?

Thank you in advance.

Related: https://github.com/cvfosammmm/Setzer/issues/194

**Comment by danastasio** [comment]
I also have this problem. I'm running latexmk from the command line as a work around, but its not my favorite thing.

Happy to provide any logs or anything requested.

**Comment by jakobjakobson13** [comment]
Yes, you are both right. But at the moment I see two problems:
- The latest texlive commit [timed](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/issues/43) [out](https://github.com/flathub/flathub/issues/2077). Therefore any new commits will just stash at the moment on top of the previous commit.
- Biber has MANY dependencies. Therefore it would be the easiest and error pronest to execute the [flatpak-cpan-generator](https://github.com/flatpak/flatpak-builder-tools/blob/master/cpan/flatpak-cpan-generator.pl) (instructions are given in the repository) on the [biber package](https://github.com/plk/biber/archive/refs/tags/v2.16.tar.gz). Unfortunately I currently fail to get a virtual machine running on my PC and my perl is too old to run this script. So could I ask you for the favor of running the script and posting its manifest? Then I would adapt the manifest.

And then we just have to convince the people from flathub to increase the time out value in their build bot configuration, so the latest commits will get published.

**Comment by hfiguiere** [comment]
The thing is that flatpak-cpan-generator failed in that case. See https://github.com/flatpak/flatpak-builder-tools/issues/174

**Comment by jakobjakobson13** [comment]
> The thing is that flatpak-cpan-generator failed in that case. See [flatpak/flatpak-builder-tools#174](https://github.com/flatpak/flatpak-builder-tools/issues/174)

Could you try to download biber, extract the archive and run the script for the `Build.PL` in the biber directory?

**Comment by fgeisser2** [comment]
I am affected by this problem, too.

This is the Manifest generated by running `Build.PL` (with file extension added for github).

[MANIFEST.txt](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/files/6682947/MANIFEST.txt)

**Comment by jakobjakobson13** [comment]
@fgeisser2 Your `MANIFEST.txt` file lists a `META.json` and `META.yml` file. Could you post them as well?

**Comment by fgeisser2** [comment]
The files are called a bit different, but these should be the correct ones:
[MYMETA.json.txt](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/files/6682997/MYMETA.json.txt)
[MYMETA.yml.txt](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/files/6682998/MYMETA.yml.txt)

**Comment by jakobjakobson13** [comment]
I fear that those files are not the ones that are needed.
Did you run the [flatpak-cpan-generator.pl](https://github.com/flatpak/flatpak-builder-tools/blob/master/cpan) on the biber archive or did you run the `MANIFEST.pl` file?

**Comment by fgeisser2** [comment]
I ran the Build.pl in the extracted archive of biber, haven't tried flatpak-cpan-generator.pl yet.

**Comment by jakobjakobson13** [comment]
> I ran the Build.pl in the extracted archive of biber, haven't tried flatpak-cpan-generator.pl yet.

Well, the flatpak-cpan-generator.pl is the one you have to try :)

**Comment by fgeisser2** [comment]
So I got flatpak-cpan-generator up and running, but I think I ran into the problem @hfiguiere had.

`Unexpected 0 releases for biblatex-biber-2.16 at biber-2.16/flatpak-cpan-generator.pl line 51.`

Is there a way to get the Manifest without flatpak-cpan-generator, or must that issue be resolved first?

**Comment by jakobjakobson13** [comment]
In principle you do not need the generator script but then you have to (a) resolve all depencies on your own and (b) get the check sum for each dependency archive. So the script helps alot.

**Comment by fkastner** [comment]
The problem for that error (`Unexpected 0 releases [...]`) is just because `biber` is not on cpan. Indeed we're trying to install it from the .tar.gz archive from github, but the script tries to find the sources on cpan.
I modified the generator script to skip biber and it outputted the following json (file ext changed because github didn't like json): 
[generated-sources.txt](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/files/7323748/generated-sources.txt)

I hope this helps to resolve this issue?

**Comment by danastasio** [comment]
I was able to get flatpak-cpan-generator running on my system finally. Here are the requested files @jakobjakobson13  

I appended .txt to the end because github wouldn't let me upload them with the original ending.

Output of flatpak-cpan-generator is:

```bash
** Installing dependencies with cpanm...
! Finding biber on cpanmetadb failed.
! Finding biber () on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution biber
cpanm failed with exit status 256
```

[MYMETA.json.txt](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/files/7471244/MYMETA.json.txt)
[MYMETA.yml.txt](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/files/7471245/MYMETA.yml.txt)
[MANIFEST.txt](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/files/7471246/MANIFEST.txt)

So, it would seem that biber is indeed no longer on cpan. Is this something you can resolve?

**Comment by jakobjakobson13** [comment]
> The problem for that error (`Unexpected 0 releases [...]`) is just because `biber` is not on cpan. Indeed we're trying to install it from the .tar.gz archive from github, but the script tries to find the sources on cpan. I modified the generator script to skip biber and it outputted the following json (file ext changed because github didn't like json): [generated-sources.txt](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/files/7323748/generated-sources.txt)
> 
> I hope this helps to resolve this issue?

@fkastner Could you share your adapted generator script for future releases?

@danastasio i'll take a look at fkastners file and will let you know about the success.

**Comment by fkastner** [comment]
It's nothing fancy. I just inserted an ´´if it's biber, don't try to get the source from cpan´´:
```perl
foreach my $dep (@deps) {
    if ($dep eq "biblatex-biber-2.16") {
      say "** Skipping $dep, source provided in .tar.gz";
    } else {
      say "** Processing: $dep";
      my $source = get_source_for_dep $cpan, $dep, $opts->dir;
      push @sources, $source;
    }
  }
```

Generally it would probably be better to detect if the argument to the script is a local .tar.gz archive and then avoid calling cpan for that. But that would also involve getting the name and version of the package from the archive and maybe some other complications so I went the easy way and special cased `biblatex-biber-2.16`.

Here's the full file again: [flatpak-cpan-generator.pl.txt](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/files/7537500/flatpak-cpan-generator.pl.txt)

**Comment by jakobjakobson13** [comment]
Could anyone help me out by testing my current manifest: https://github.com/jakobjakobson13/org.freedesktop.Sdk.Extension.texlive/tree/biblatex . It builds without errors, but I can´t run it locally at my computer and don´t know why.

**Comment by jakobjakobson13** [comment]
> It's nothing fancy. I just inserted an ´´if it's biber, don't try to get the source from cpan´´:
> 
> ```perl
> foreach my $dep (@deps) {
>     if ($dep eq "biblatex-biber-2.16") {
>       say "** Skipping $dep, source provided in .tar.gz";
>     } else {
>       say "** Processing: $dep";
>       my $source = get_source_for_dep $cpan, $dep, $opts->dir;
>       push @sources, $source;
>     }
>   }
> ```
> 
> Generally it would probably be better to detect if the argument to the script is a local .tar.gz archive and then avoid calling cpan for that. But that would also involve getting the name and version of the package from the archive and maybe some other complications so I went the easy way and special cased `biblatex-biber-2.16`.
> 
> Here's the full file again: [flatpak-cpan-generator.pl.txt](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive/files/7537500/flatpak-cpan-generator.pl.txt)

Thank you. That helped a lot.

**Comment by fkastner** [comment]
> Could anyone help me out by testing my current manifest: https://github.com/jakobjakobson13/org.freedesktop.Sdk.Extension.texlive/tree/biblatex . It builds without errors, but I can´t run it locally at my computer and don´t know why.

Could you PR your current manifest to this repo? Then the bot would start a test build which we could then examine.
See https://github.com/flathub/flathub/wiki/App-Maintenance#test-builds-and-pull-requests

**Comment by jakobjakobson13** [comment]
> Could you PR your current manifest to this repo? Then the bot would start a test build which we could then examine. See https://github.com/flathub/flathub/wiki/App-Maintenance#test-builds-and-pull-requests

I did not want to spam the flathub bot with half-baked solutions. But there we go: #59 .

**Comment by danastasio** [comment]
looks like the build succeeded @jakobjakobson13. Is there anything else we need to do, or is this good to go?

**Comment by danastasio** [comment]
@jakobjakobson13 this still isn't showing up in TexLive. I'm trying to use it as part of Setzer, where the build is failing. There is an open issue there (cvfosammmm/Setzer#194) and the dev is blaming texlive. Can you provide any insight? Thanks.

**Comment by hfiguiere** [comment]
there are issues that need to be addressed *with* texlive, it's complicated. I was looking at that to provide a fix.

**Comment by hfiguiere** [comment]
But Setzer (the flatpak) should upgrade to GNOME 41 runtime, for starter, as all of this is in the 21.08 branch. Also given how it used the texlive SDK it should actually work out of the box once this is done.

**Comment by hfiguiere** [comment]
@danastasio there will be a test build on https://github.com/flathub/org.cvfosammmm.Setzer/pull/14

This should have a working Biber. I'm not sure how to test it properly though (I'm not fluent in LaTeX, even less BibTex)

Let me know.

**Comment by danastasio** [comment]
Thanks! I have a bunch of files I can test with. As soon as the build passes I'll check it out.

**Comment by fgeisser2** [comment]
I build the branch gnome41-branch of Setzer myself and biber seems to work fine.

**Comment by hfiguiere** [comment]
I have that PR open for Setzer https://github.com/flathub/org.cvfosammmm.Setzer/pull/14

But it failed for some reason on aarch64 and was trying to debug that locally

Good to know it's working.

**Comment by hfiguiere** [comment]
note that it requires rebuilding Perl in the Setzer flatpak
