### ISSUE TITLE
20.08 requires 4.3GB of space

### ISSUE THREAD

**Issue by kowalcj0** [flathub/org.freedesktop.Sdk.Extension.texlive#51]
Hi,
This rather remarkable that texlive requires that much space:
![Image6794937397979329153](https://user-images.githubusercontent.com/910451/125536614-efc3efe6-6665-4b28-a2b5-d5e1614d1013.jpg)
Is it possible that some tmp build files got into the release ?

Thanks

**Comment by hfiguiere** [comment]
it's not 

see https://tug.org/texlive/acquire-iso.html

**Comment by kowalcj0** [comment]
Hi @hfiguiere 
I'm not sure I follow, the link you provided says that the iso size is almost 4GB, and flatpak says that it's going to download 4.3GB. 
It'd be great if maintainers provided some insights on this topic.
Thank you

**Comment by hfiguiere** [comment]
It is big in the same order of magnitude. If texlive was 200MB and this flatpak 4.3GB I wouldn't even be arguing there is a problem.

Also this is rebuilt from source, and it includes things that are not part of texlive because texlive has requirements that are usually fullfilled by the distribution that we have to provide here. Like Ghostscript.

**Comment by kowalcj0** [comment]
Let's close this ticket, cos it won't get anywhere.
Will simply uninstall Anki cos it's not worth of additional 4GB of space.

**Comment by hfiguiere** [comment]
The related package was fixed FWIW. Without being antagonistic.

**Comment by kowalcj0** [comment]
Hi, 
I think we misunderstood each other. I wasn't complaining about the difference in size between flatpak and upstream :)
What I was trying to point out, is that it's pretty ridiculous for a typesetting system to take up so much space.
For the sake of comparison, installing `texlive` via DNF will gobble up 10x less space:
![image](https://user-images.githubusercontent.com/910451/125754121-c6c91546-77db-4076-b433-6ba31ecc0b3b.png)
I understand that said iso contains more than a *nix user might ever need, as it contain binaries for all major operating systems:

> It provides a comprehensive TeX system with binaries for most flavors of Unix, including GNU/Linux, macOS, and also Windows.
https://tug.org/texlive/

The question is, why a *nix user needs all of that? (keeping in mind that probably plenty of users don't have much inclination towards understanding the history of texlive)
Based on this thread, my current understanding is that this flatpak provides pretty much a 1-to-1 copy of said iso, which is a texlive SDK. 
So, maybe you're right, I should first ask maintainers of Anki about the purpose of using SDK instead of some minimal subset of tools required to provide a TeX support in their application.

Thanks
