### ISSUE TITLE
texlive 2021 is missing libc

### ISSUE THREAD

**Issue by jakobjakobson13** [flathub/org.freedesktop.Sdk.Extension.texlive#58]
When I tried the texlive 2021

    TeX Live Sdk extension - LaTeX packages and tools

     Kennung: org.freedesktop.Sdk.Extension.texlive
         Ref: runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/21.08
    Architektur: x86_64
       Zweig: 21.08
     Version: 2020.04.06
    Ursprung: flathub
    Sammlung: org.flathub.Stable
    Installation: user
     Installiert: 7,5 GB

      Commit: e60f2fc6050a325d6311275a1e9509d841d031ba1f33d6d3803e31e5e9508b17
     Subject: Update SDK and runtime to 21.08 (d2fc5c7f)
        Date: 2021-10-21 08:55:18 +0000

with a provisonary version of [texworks](https://github.com/flathub/org.tug.texworks/pull/13)

     TeXworks - Eine einfache Umgebung zum Bearbeiten, Setzen und Darstellen von
    TeX-Dokumenten

         Kennung: org.tug.texworks
             Ref: app/org.tug.texworks/x86_64/test
     Architektur: x86_64
           Zweig: test
         Version: 0.6.6
         License: GPL-2.0+
        Ursprung: texworks-origin
        Sammlung: org.flathub.Stable.Build63006
    Installation: user
     Installiert: 114,6 MB
    Laufzeitumgebung: org.kde.Platform/x86_64/5.15
             Sdk: org.kde.Sdk/x86_64/5.15

          Commit: 593d8b3ecf4c9d340216d42f89f7ae45ea013fa0ea31c5565d542388980ab…
         Subject: Update org.tug.texworks.yaml (8e4c6355)
            Date: 2021-10-28 20:49:29 +0000

I ran into the following error messages

    [📦 org.tug.texworks ~]$ lualatex
    lualatex: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by lualatex)
    [📦 org.tug.texworks ~]$ pdflatex
    pdflatex: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by pdflatex)

Does this error message derive from my quite conservative (glibc is provided in version `2.26`) Suse 15.2 installation or are we having an error in the flatpak package?

**Comment by hfiguiere** [comment]
My comment: you need to update the runtime too.

**Comment by hfiguiere** [comment]
kde 5.15 is based on 20.08. There is a kde 5.15-21.08

**Comment by jakobjakobson13** [comment]
This issue was solved by hfiguiere´s hint, see https://github.com/flathub/org.tug.texworks/pull/14 .
