### ISSUE TITLE
(acro) package outdated

### ISSUE THREAD

**Issue by rugk** [flathub/org.freedesktop.Sdk.Extension.texlive#9]
If I am correct (see https://github.com/flathub/org.texstudio.TeXstudio/issues/31) I can report this here. I use the TeXStudio from flathub, and I see the acro package is still outdated (some 2018 variant).

I notice this, because the old version of acro does not support `foreign-plural`. (I have no idea how to display the version that is used inside the flatpak.)

Same as the Fedora package BTW: https://bugzilla.redhat.com/show_bug.cgi?id=1759296 (maybe it's also the [general update for 2019 that is missing](https://bugzilla.redhat.com/show_bug.cgi?id=1758043))

**Comment by rugk** [comment]
Okay, actually the issue may be https://tex.stackexchange.com/questions/420043/package-acro-does-not-work-with-biblatex-anymore?noredirect=1, so maybe rather the biber package is outdated??

**Comment by jakobjakobson13** [comment]
@rugk Can you check if the bug is still valid after the last update to texlive 2019?

**Comment by rugk** [comment]
Nah, still getting the error in TeXStudio (don't know how to show the version of acro, however):

![grafik](https://user-images.githubusercontent.com/11966684/67373273-a3d7ee80-f57f-11e9-8c15-7f0520ee94bc.png)

**Comment by jakobjakobson13** [comment]
@rugk:
- Could you check if there is a log file in your current directory? This file should include the packages and their versions that have been used for compiling your document.
- Also could you check your bug against a manual texlive installation?

**Comment by rugk** [comment]
Ah, a log, of course. Here some important things I found:
```
(/app/texmf-dist/tex/latex/acro/acro.sty
(/app/texmf-dist/tex/latex/l3kernel/expl3.sty
Package: expl3 2018/03/05 L3 programming layer (loader) 

(/app/texmf-dist/tex/latex/l3kernel/expl3-code.tex
Package: expl3 2018/03/05 L3 programming layer (code)
\ucharcat@table=\catcodetable7
[…]
Package: acro 2017/01/30 v2.8 Typeset Acronyms
\l__acro_tmpa_int=\count195
\l__acro_tmpb_int=\count196
\l__acro_tmpc_int=\count197
\l__acro_tmpd_int=\count198
\l__acro_page_space_skip=\skip67
\l__acro_short_width_dim=\dimen159
```

> Also could you check your bug against a manual texlive installation?

As said in the OP:
> Same as the Fedora package BTW: https://bugzilla.redhat.com/show_bug.cgi?id=1759296 (maybe it's also the general update for 2019 that is missing)

So there it also happens… (only on a Windows installation with up-to-date packages this issue did not occur)

**Comment by jakobjakobson13** [comment]
Could you post the first line of your log file? It should look similar to the following `This is LuaTeX, Version 1.0.4 (TeX Live 2017/Debian)  (format=lualatex 2019.3.27)`.

**Comment by rugk** [comment]
> This is LuaTeX, Version 1.07.0 (TeX Live 2018)  (format=lualatex 2019.2.20)  23 OCT 2019 10:26

:thinking: (Yes, I did `flatpak update`  before :thinking: )

**Comment by jakobjakobson13** [comment]
The problem is the following:

```bash
$ /var/lib/flatpak/runtime/org.freedesktop.Sdk.Extension.texlive/x86_64/18.08/13b1f85825d4fd40fd90b59bf680ac90a47d1b04f9d1c042e7daa74cc4a5a052/files/bin/x86_64-linux/pdflatex TexLiveSdkTest.tex 
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex)


$ /var/lib/flatpak/app/org.texstudio.TeXstudio/x86_64/stable/5bbbc114485cb314b75f14eb3deea3b16448b782ab4350e0a250e14a6852f07b/files/bin/x86_64-linux/pdflatex TexLiveSdkTest.tex 
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018) (preloaded format=pdflatex)
```

The `org.freedesktop.Sdk.Extension.texlive` got updated but `org.texstudio.TeXstudio` uses its own binary that has probably (that's my guess, at least) been copied from the `org.freedesktop.Sdk.Extension.texlive` earlier. And so an update of `org.freedesktop.Sdk.Extension.texlive` does not show any effect on the the binaries that are used by `org.texstudio.TeXstudio`. But I don't know how to solve this issue.

**Comment by rugk** [comment]
Okay, reported at https://github.com/flathub/org.texstudio.TeXstudio/issues/33

**Comment by jakobjakobson13** [comment]
@rugk Could you please check if this bug report still applies with the latest update?

**Comment by rugk** [comment]
Thanks. Works now:
> This is LuaTeX, Version 1.07.0 (TeX Live 2018)  (format=lualatex 2019.2.20)  9 NOV 2019 10:29
